[package]
name = "comelit-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "client",
    "hap",
    "tui",
]

[lib]
name = "comelit_hub"

[profile.release]
opt-level = "z"      # o "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
