name: Windows msi

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release --manifest-path hap/Cargo.toml

      - name: Install WiX
        run: choco install wixtoolset -y

      - name: Prepare files
        run: |
          mkdir installer\msi\bin
          copy target\release\comelit-hub-hap.exe installer\msi\bin\

      - name: Build MSI
        run: |
          candle hap\installer\msi\product.wxs
          light product.wixobj -out comelit-hub-hap.msi

      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: comelit-hub-hap-msi
          path: comelit-hub-hap.msi
